services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      args:
        SERVICE: api
    image: queue-api:latest
    environment:
      REDIS_HOST: redis
      PORT: "3000"
      REDIS_PORT: "6379"
    ports:
      - "3000:3000"
    depends_on:
      - redis

  worker:
    build:
      context: .
      args:
        SERVICE: worker
    image: queue-worker:latest
    environment:
      REDIS_HOST: redis
      METRICS_PORT: "9100"
      REDIS_PORT: "6379"
    ports:
      - "9100:9100"
    cpus: 0.5
    mem_limit: 512m
    depends_on:
      - redis

  stats:
    build:
      context: .
      args:
        SERVICE: stats
    image: queue-stats:latest
    environment:
      REDIS_HOST: redis
      PORT: "3100"
      REDIS_PORT: "6379"
    ports:
      - "3100:3100"
    depends_on:
      - redis
