apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker
  namespace: queue-system
spec:
  selector:
    matchLabels:
      app: worker
  namespaceSelector:
      matchNames:
        - queue-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stats
  namespace: queue-system
spec:
  selector:
    matchLabels:
      app: stats
  namespaceSelector:
    matchNames:
      - queue-system
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
